cadena = input("Introduce una palabra:")
numero = int(input("Introduce un numero:"))
decimal = float(input("Introduce un numero con decimales:"))
print(cadena)
print(numero)
print(decimal)
print(type(cadena))
print(type(numero))
print(type(decimal))